global:
  yml_type: DET
  train_model_path: ./output/model_det/best_hmean.pth
  infer_model_path: ./output/model_det/DBNet.onnx
  res_save_dir: ./output/result_det
  use_infer_model: true

logger:
  name: detection
  level: INFO

Architecture:
  model_type: det
  algorithm: DBNet
  Backbone:
    name: det_mobilenet_v3
    pre_trained_dir:
    multiplier: 0.5
    use_se: false
    # name: resnet34
    # pre_trained_dir:
  Neck:
    name: DBFPN
    inner_channel: 96
  Head:
    name: DBHead
    k: 50

post_process:
  name: DBPostProcess
  thresh: 0.3
  box_thresh: 0.6
  max_candidates: 1000
  unclip_ratio: 1.6

dataset:
  image_dir_or_path: ./data_loader/det/test
  transforms:
    - ResizeForTest:
        long_size: 960
    - NormalizeImage:
    - OutputData:
        keep_keys: ["image", "src_scale"]


