global:
  yml_type: REC
  train_model_path: ./output/model_rec/rec_train.pth
  infer_model_path: ./output/model_rec/CRNN.onnx
  res_save_dir: ./output/result_rec
  use_infer_model: true
  character_json_path: ./data_loader/rec/num_chars_38.json

logger:
  name: recoginition
  level: INFO

Architecture:
  algorithm: CRNN
  Backbone:
    name: rec_mobilenet_v3
    pre_trained_dir:
    multiplier: 0.5
    use_se: false
    # name: rec_resnet18
    # pre_trained_dir:
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    rnn_type: GRU
    hidden_size: 48
    num_layers: 2
    bidirectional: true
  Head:
    name: CTCHead

post_process:
  name: CRnnPostProcess

dataset:
  image_dir_or_path: ./data_loader/rec/test
  transforms:
    - RecResizeImg:
        image_shape: [3, 32, 320]
    - OutputData:
        keep_keys: ['image']