global:
  yml_type: REC
  use_gpu: false
  epochs: 200
  eval_epoch: 10
  save_pth_dir: ./output/model_rec/
  init_pth_path:
  log_iter: 10
  save_epoch_iter: 10
  max_text_len: 18
  character_json_path: ./data_loader/rec/num_chars_38.json

logger:
  name: recognition
  level: INFO

optimizer:
  name: OptimizerScheduler
  optim_method: _adam
  init_learning_rate: 0.001
  learning_schedule:
    name: LearningSchedule
    lr_method: _cosine_warmup
    warmup_epoch: 2

Architecture:
  model_type: rec
  algorithm: CRNN
  Transform:
  Backbone:
    name: rec_mobilenet_v3
    pre_trained_dir:
    multiplier: 0.5
    use_se: false
    # name: rec_resnet18
    # pre_trained_dir: ./pretrained/rec/resnet50-19c8e357.pth
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    rnn_type: GRU
    hidden_size: 48
    num_layers: 2
    bidirectional: true
  Head:
    name: CTCHead

loss:
  name: CTCLoss

post_process:
  name: CRnnPostProcess

metrics:
  name: RecMetric
  main_indicator: acc

train:
  dataset:
    name: RecDataSet
    data_base_dir: ./data_loader/rec
    ano_file_path: ./data_loader/rec/train.txt
    do_shuffle: true
    transforms:
      - RecAug:
          aug_prob: 0.4
      - RecResizeImg:
          image_shape: [3, 32, 320]
      - OutputData:
          keep_keys: ['image', 'sequence_length', 'label_idx']
  dataloader:
    batch_size: 2
    num_workers: 0
    drop_last: true
    pin_memory: true

validate:
  dataset:
    name: RecDataSet
    data_base_dir: ./data_loader/rec
    ano_file_path: ./data_loader/rec/val.txt
    do_shuffle: false
    transforms:
      - RecResizeImg:
          image_shape: [3, 32, 320]
      - OutputData:
          keep_keys: ['image', 'sequence_length', 'label_idx']
  dataloader:
    batch_size: 1
    num_workers: 0
    drop_last: false
    pin_memory: false
