global:
  infer_det_path: ./output/model_det1/latest.onnx
  infer_rec_path: ./output/model_rec/rec.onnx
  res_save_dir: ./output/result_liteocr
  image_dir_or_path: ./data_loader/rec/test
  character_json_path: ./data_loader/rec/num_chars_38.json

det:
  post_process:
    name: DBPostProcess
    thresh: 0.3
    box_thresh: 0.6
    max_candidates: 1000
    unclip_ratio: 1.6
  transforms:
    - ResizeForTest:
      long_size: 960
    - NormalizeImage:
    - OutputData:
        keep_keys: ["image", "src_scale"]

rec:
  post_process:
    name: CRnnPostProcess
